version: "3.8"

services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    container_name: paytm-backend

  frontend:
    build:
      context: ./Frontend/my-app
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    depends_on:
      - backend
    container_name: paytm-frontend
