name: Docker Build, Push & Deploy

on:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: docker  # ← ADD THIS LINE
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/paytm-backend:latest

  frontend:
    runs-on: ubuntu-latest
    environment: docker  # ← ADD THIS LINE
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend/my-app
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/paytm-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    environment: docker  # ← ADD THIS LINE
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/paytm/
          if [ -f Backend/.env ]; then
            scp -o StrictHostKeyChecking=no Backend/.env ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/paytm/
          fi

      - name: SSH into EC2 and deploy
        run: |
          cat > deploy.sh << 'SCRIPT'
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose-plugin
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ubuntu || true
          cd ~/paytm
          echo '${{ secrets.DOCKER_HUB_PASSWORD }}' | sudo docker login -u '${{ secrets.DOCKER_HUB_USERNAME }}' --password-stdin
          sudo docker-compose pull
          sudo docker-compose up -d --build
          SCRIPT
          
          scp -o StrictHostKeyChecking=no deploy.sh ubuntu@${{ secrets.EC2_PUBLIC_IP }}:~/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "chmod +x ~/deploy.sh && ~/deploy.sh"